///////////////////////////////////////////////////////////////////////////////
// clientClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "clientClassFactory.h"
#include "clientServices.h"
#include "clientVersion.h"
#include "Client.h"

BEGIN_CLASS_MAP(CclientClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY(CID_clientCClient, SRVNAME_CLIENT "!CClient", CClient)
///</AutoGeneratedContent>
END_CLASS_MAP()

CclientClassFactory::CclientClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_CLIENT));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(client));
#endif //defined(TCDBG_UNIT_VERSION)
}

