///////////////////////////////////////////////////////////////////////////////
// clientServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_client = 0x3F000000;
#define SRVNAME_CLIENT "client"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_clientCClient = {0xee9f1864,0x8bc7,0x4b04,{0xb2,0x6b,0xe9,0xe2,0x68,0xf2,0x23,0x9b}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_ClientDefaultAdsPort = 0x00000001;
const PTCID PID_ClientCounter = 0x00000003;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _ClientInputs
{
	ULONG Value;
	ULONG Status;
	ULONG Data;
} ClientInputs, *PClientInputs;

typedef struct _ClientOutputs
{
	ULONG Value;
	ULONG Control;
	ULONG Data;
} ClientOutputs, *PClientOutputs;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_ClientInputs 0
#define ADI_ClientOutputs 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
